name: Publish Docker image

on:
  push:
    # 每次 push tag 时进行构建，不需要每次 push 都构建。使用通配符匹配每次 tag 的提交，记得 tag 名一定要以 v 开头
    tags: 
      - v*
  

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: luoqiz/zerotier-moon

jobs:
  release:
    
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        
      - name: Get version
        id: get_version
        run: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}" 
